pull_request_rules:
  - name: Automatic comment on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      comment:
        message: Hello there, Happy Hacktoberfest. Dont't forget to :star:! the repo.